function GoogleMap() {
    return (
        <div className="maps">
            <div className="mapsSom">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7888.131415996297!2d69.25113504509895!3d41.317382485347125!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38ae8b40d847941d%3A0x5765a18b352df71e!2sTashkent%20City%20Park!5e0!3m2!1sru!2s!4v1683975196872!5m2!1sru!2s" width="600" height="450" style={{border: 0 }} allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

            </div>
            
        </div>
    )
}
export default GoogleMap

{/* <ymaps className="ymaps-2-1-79-map" style="width: 373px; height: 480px;">
            <ymaps class="ymaps-2-1-79-map ymaps-2-1-79-i-ua_js_yes ymaps-2-1-79-map-bg ymaps-2-1-79-islets_map-lang-ru" style="width: 373px; height: 480px; z-index: 0;"><ymaps class="ymaps-2-1-79-inner-panes">
            <ymaps class="ymaps-2-1-79-events-pane ymaps-2-1-79-user-selection-none" unselectable="on" style="height: 100%; width: 100%; top: 0px; left: 0px; position: absolute; z-index: 3000; cursor: url(&quot;https://api-maps.yandex.ru/2.1.79/build/release/images/cursor/grab.cur&quot;) 16 16, url(&quot;https://api-maps.yandex.ru/2.1.79/build/release/images/cursor/grab.cur&quot;), move;">
            </ymaps>
            <ymaps class="ymaps-2-1-79-ground-pane" style="top: 0px; left: 0px; position: absolute; transform: translate3d(0px, 0px, 0px) scale(1, 1); z-index: 601;">
            <ymaps style="z-index: 150; position: absolute;">
            <canvas height="1472" width="1258" style="position: absolute; width: 629px; height: 736px; left: -128px; top: -128px;">
            </canvas>
            </ymaps>
            </ymaps>
            <ymaps class="ymaps-2-1-79-copyrights-pane" style="height: 0px; inset: auto 0px 0px; position: absolute; z-index: 6002;">
            <ymaps>
            <ymaps class="ymaps-2-1-79-copyright" style="">
            <ymaps class="ymaps-2-1-79-copyright__fog">
            </ymaps>
            <ymaps class="ymaps-2-1-79-copyright__wrap"><ymaps class="ymaps-2-1-79-copyright__layout">
            <ymaps class="ymaps-2-1-79-copyright__content-cell">
            <ymaps class="ymaps-2-1-79-copyright__content">
            <ymaps class="ymaps-2-1-79-copyright__text">© Яндекс</ymaps>
            <ymaps class="ymaps-2-1-79-copyright__agreement">&nbsp;<a class="ymaps-2-1-79-copyright__link" target="_blank" href="https://yandex.ru/legal/maps_termsofuse/?lang=ru" rel="noopener">Условия</a></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-copyright__logo-cell">
            <a class="ymaps-2-1-79-copyright__logo" href="" target="_blank">
            </a>
            </ymaps>
            </ymaps>
            </ymaps>
            </ymaps>
            </ymaps>
            </ymaps>
            <ymaps class="ymaps-2-1-79-controls-pane" style="width: 100%; top: 0px; left: 0px; position: absolute; z-index: 5403;">
            <ymaps class="ymaps-2-1-79-controls__toolbar" style="margin-top: 10px;">
            <ymaps class="ymaps-2-1-79-controls__toolbar_left">
            </ymaps><ymaps class="ymaps-2-1-79-controls__toolbar_right">
            </ymaps>
            </ymaps>
            <ymaps class="ymaps-2-1-79-controls__bottom" style="top: 480px;">
            </ymaps>
            </ymaps>
            <ymaps class="ymaps-2-1-79-places-pane" style="top: 0px; left: 0px; position: absolute; transform: translate3d(0px, 0px, 0px) scale(1, 1); z-index: 2404;">
            <ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -152px; top: 364px;">
            <ymaps>
            <ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);">
            </ymaps></ymaps></ymaps>
            <ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -283px; top: 335px;">
            <ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps>
            </ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -283px; top: 335px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps>
            <ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -271px; top: 328px;"><ymaps>
            <ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -279px; top: 343px;">
            <ymaps>
            <ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps>
            </ymaps></ymaps>
            <ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -272px; top: 326px;"><ymaps>
            <ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps>
            <ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -279px; top: 326px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps>
            <ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -274px; top: 328px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -213px; top: 292px;"><ymaps>
            <ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -205px; top: 298px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps>
            <ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -272px; top: 333px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -272px; top: 333px;"><ymaps>
            <ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -280px; top: 334px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps>
            <ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -266px; top: 325px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -280px; top: 336px;"><ymaps>
            <ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -409px; top: 475px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -485px; top: 527px;"><ymaps>
            <ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -486px; top: 525px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -271px; top: 323px;"><ymaps>
            <ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -271px; top: 330px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps>
            <ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -278px; top: 329px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -272px; top: 330px;"><ymaps>
            <ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: 7px; top: 393px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -264px; top: 325px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -486px; top: 525px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);">
            </ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -57px; top: 368px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -57px; top: 368px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -42px; top: 443px;">
            <ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -45px; top: 441px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -121px; top: 422px;">
            <ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -122px; top: 423px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -269px; top: 328px;">
            <ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -275px; top: 331px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps>
            </ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -282px; top: 325px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -279px; top: 330px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -265px; top: 326px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);">
            </ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -279px; top: 324px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -269px; top: 331px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps>
            </ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -275px; top: 327px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -275px; top: 327px;"><ymaps>
            <ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -274px; top: 328px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps>
            </ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -2818px; top: -4400px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -212px; top: 308px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-placemark-overlay ymaps-2-1-79-user-selection-none" unselectable="on" style="z-index: 650; height: 0px; width: 0px; position: absolute; left: -271px; top: 328px;"><ymaps><ymaps class="ymaps-2-1-79-image " style="position: absolute; left: -11px; top: -38px; width: 40px; height: 40px; opacity: 1; background-position: 0px 0px; background-size: 40px 40px; background-image: url(&quot;https://tokbor.uz/themes/tokbor-oz/driver/img/icon/baloon.png&quot;);"></ymaps></ymaps></ymaps></ymaps><ymaps class="ymaps-2-1-79-balloon-pane" style="top: 0px; left: 0px; position: absolute; transform: translate3d(0px, 0px, 0px) scale(1, 1); z-index: 4205;"></ymaps></ymaps></ymaps></ymaps> */}