import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Statistika from '@/components/statistika/Statistika'
import Mijozlar from '@/components/Mijozlar/Mijozlar'
import Ilova from '@/components/ilova/Ilova'
import Hamkorlik from '@/components/hamkorlik/Hamkorlik'
import Taklif from '@/components/taklif/Taklif'
import Malumot from '@/components/malumot/Malumot'
import Start from '@/components/start/Start'
import GoogleMap from '@/components/googleMap/GoogleMap'
import Offer from '@/components/offer/Offer'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'


export async function getStaticProps({locale}) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['home']))
    }
  }
}
export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main'>
        <Offer/>
        <Statistika/>
        {/* <h1>{t('home:welcome_msg')}</h1>  test uchun yaratilgan */}
        <Mijozlar/>
        <Ilova/>
        <Hamkorlik/>
        <Taklif/>
        <Malumot/>
        <Start/>
        <GoogleMap/>
      </main>
    </>
  )

  // return (
  //   <h1>welcome to my sakai</h1>
  // )
}
